### ISSUE TITLE
Fails to build when including xlocale.h

### ISSUE THREAD

**Issue by tphecca** [FasterMelee/Ishiiruka#3]
From within Ubuntu 17.10, compiling fails with this:
```
Ishiiruka-master/Externals/wxWidgets3/include/wx/xlocale.h:44:18: fatal error: xlocale.h: No such file or directory
         #include <xlocale.h>
                  ^~~~~~~~~~~
compilation terminated.
```

However, I looked up information about `xlocale.h` and found that it's only a subset of `locale.h`, and that `xlocale.h` was removed in the latest glibc. I linked the correct file in the filesystem like so:
```
ln -s /usr/include/locale.h /usr/include/xlocale.h
```

I'm not a C developer so I'm not sure, but it seems like one should be able to change the includes of `xlocale.h` to include `locale.h` instead. Apparently this is what upstream Dolphin did, because it has always built and ran correctly on Ubuntu 17.10.

**Comment by Ptomerty** [comment]
This has been supported in the official installer since 9/17/2017: https://github.com/FasterMelee/FasterMelee-installer/commit/4f3cdebf8df3fce7ef0deaadbb6b293295370f79

However, I've added it to the main repo (finally!) here: https://github.com/FasterMelee/Ishiiruka/commit/029a51be86a87d8452caaff5dd97e626cdf1b49e

Closing.
